import os

CWD = os.path.dirname(__file__)
HTML_PATH = CWD + '/htmls/'
IMG_PATH = CWD + '/img/'

# page1
WORD_CLOUD_WIDTH = '600px'
WORD_CLOUD_HEIGHT = '340px'
HISTORICAL_DATA_WIDTH = '580px'
HISTORICAL_DATA_HEIGHT = '350px'

# page2
NEWS_TRENDING_LINE_CHART_WIDTH = '800px'
NEWS_TRENDING_LINE_CHART_HEIGHT = '215px'

# page3
HISTORY_PRICE_SCORE_LINE_CHART_WIDTH = '580px'
HISTORY_PRICE_SCORE_LINE_CHART_HEIGHT = '285px'