# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\souththzz\OneDrive\Data\FINTECH80\UI\fintech-ui\signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setStyleSheet("*{\n"
"    font: 14px \"Microsoft YaHei\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius:30px;\n"
"    background-color: white;\n"
"}")
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leftFrame = QtWidgets.QFrame(self.frame)
        self.leftFrame.setStyleSheet("")
        self.leftFrame.setObjectName("leftFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.leftFrame)
        self.horizontalLayout_6.setContentsMargins(0, 150, 0, 150)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(400, 350))
        self.label_3.setMaximumSize(QtCore.QSize(400, 350))
        self.label_3.setStyleSheet("border-image: url(:/img/welcome.svg);")
        self.label_3.setText("")
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_4.addWidget(self.leftFrame)
        self.rightFrame = QtWidgets.QFrame(self.frame)
        self.rightFrame.setObjectName("rightFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rightFrame)
        self.verticalLayout_3.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(self.rightFrame)
        self.closeButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background: none;\n"
"}")
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setIconSize(QtCore.QSize(24, 24))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.stackedWidget = QtWidgets.QStackedWidget(self.rightFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.signinPage = QtWidgets.QWidget()
        self.signinPage.setObjectName("signinPage")
        self.loginForm = QtWidgets.QFrame(self.signinPage)
        self.loginForm.setGeometry(QtCore.QRect(0, 0, 481, 701))
        self.loginForm.setObjectName("loginForm")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginForm)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.loginForm)
        self.label_2.setStyleSheet("QLabel{\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(self.loginForm)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    font-size: 16px;\n"
"    border-radius: 8px;\n"
"    background: whitesmoke;\n"
"    padding: 10px;\n"
"    min-height:40px;\n"
"    max-height:40px;\n"
"}")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.loginForm)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    font-size: 16px;\n"
"    border-radius: 8px;\n"
"    background: whitesmoke;\n"
"    padding: 10px;\n"
"    min-height:40px;\n"
"    max-height:40px;\n"
"}")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.loginForm)
        self.checkBox.setIconSize(QtCore.QSize(16, 16))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_2 = QtWidgets.QPushButton(self.loginForm)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    background: none;\n"
"    text-decoration: underline;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.signinButton = QtWidgets.QPushButton(self.loginForm)
        self.signinButton.setMinimumSize(QtCore.QSize(0, 60))
        self.signinButton.setStyleSheet("QPushButton{\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    border-radius: 30px;\n"
"    background: #536DFE;\n"
"    padding: 10px;\n"
"    min-height:40px;\n"
"    max-height:40px;\n"
"}")
        self.signinButton.setObjectName("signinButton")
        self.verticalLayout.addWidget(self.signinButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.loginForm)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.goSignupButton = QtWidgets.QPushButton(self.loginForm)
        self.goSignupButton.setStyleSheet("QPushButton{\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    background: none;\n"
"    text-decoration: underline;\n"
"}")
        self.goSignupButton.setObjectName("goSignupButton")
        self.horizontalLayout_2.addWidget(self.goSignupButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.stackedWidget.addWidget(self.signinPage)
        self.signupPage = QtWidgets.QWidget()
        self.signupPage.setObjectName("signupPage")
        self.loginForm_2 = QtWidgets.QFrame(self.signupPage)
        self.loginForm_2.setGeometry(QtCore.QRect(0, 0, 481, 701))
        self.loginForm_2.setObjectName("loginForm_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.loginForm_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.label_4 = QtWidgets.QLabel(self.loginForm_2)
        self.label_4.setStyleSheet("QLabel{\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.loginForm_2)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    font-size: 16px;\n"
"    border-radius: 8px;\n"
"    background: whitesmoke;\n"
"    padding: 10px;\n"
"    min-height:40px;\n"
"    max-height:40px;\n"
"}")
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.loginForm_2)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    font-size: 16px;\n"
"    border-radius: 8px;\n"
"    background: whitesmoke;\n"
"    padding: 10px;\n"
"    min-height:40px;\n"
"    max-height:40px;\n"
"}")
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 44, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem9)
        self.signupButton = QtWidgets.QPushButton(self.loginForm_2)
        self.signupButton.setMinimumSize(QtCore.QSize(0, 60))
        self.signupButton.setStyleSheet("QPushButton{\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    border-radius: 30px;\n"
"    background: #536DFE;\n"
"    padding: 10px;\n"
"    min-height:40px;\n"
"    max-height:40px;\n"
"}")
        self.signupButton.setObjectName("signupButton")
        self.verticalLayout_4.addWidget(self.signupButton)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.label_5 = QtWidgets.QLabel(self.loginForm_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.goSigninButton = QtWidgets.QPushButton(self.loginForm_2)
        self.goSigninButton.setStyleSheet("QPushButton{\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    background: none;\n"
"    text-decoration: underline;\n"
"}")
        self.goSigninButton.setObjectName("goSigninButton")
        self.horizontalLayout_7.addWidget(self.goSigninButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.stackedWidget.addWidget(self.signupPage)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.rightFrame)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Welcome back!"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "User"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkBox.setText(_translate("MainWindow", "Remember me"))
        self.pushButton_2.setText(_translate("MainWindow", "Forgot my password"))
        self.signinButton.setText(_translate("MainWindow", "Sign in"))
        self.label.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.goSignupButton.setText(_translate("MainWindow", "Sign up"))
        self.label_4.setText(_translate("MainWindow", "Create Your Account"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "User"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Password"))
        self.signupButton.setText(_translate("MainWindow", "Sign in"))
        self.label_5.setText(_translate("MainWindow", "Already have an account?"))
        self.goSigninButton.setText(_translate("MainWindow", "Sign in"))
import img_rc
